In [249]:
import pandas as pd

In [250]:
# machine data
liw_feeders_1 = pd.read_csv("MSOM data external sharing\Machine data\LiW Feeders 1.csv")
liw_feeders_2 = pd.read_csv("MSOM data external sharing\Machine data\LiW Feeders 2.csv")
blenders = pd.read_csv("MSOM data external sharing\Machine data\Blenders.csv")
pressor = pd.read_csv("MSOM data external sharing\Machine data\Tablet Press.csv")
temperature = pd.read_csv("MSOM data external sharing\Machine data\Temperature.csv")
humidity = pd.read_csv("MSOM data external sharing\Machine data\Humidity.csv")

C:\Users\User\AppData\Local\Temp\ipykernel_19700\4085920741.py:2: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  liw_feeders_1 = pd.read_csv("MSOM data external sharing\Machine data\LiW Feeders 1.csv")
C:\Users\User\AppData\Local\Temp\ipykernel_19700\4085920741.py:3: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  liw_feeders_2 = pd.read_csv("MSOM data external sharing\Machine data\LiW Feeders 2.csv")
C:\Users\User\AppData\Local\Temp\ipykernel_19700\4085920741.py:4: DtypeWarning: Columns (1,2,3,4,5,6) have mixed types. Specify dtype option on import or set low_memory=False.
  blenders = pd.read_csv("MSOM data external sharing\Machine data\Blenders.csv")
C:\Users\User\AppData\Local\Temp\ipykernel_19700\4085920741.py:5: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  pressor = pd.read_csv("MSOM data external sharing\Machine data\Tablet Press.csv")

In [272]:
#liw_feeder日期處理
def parse_mixed_date(date_str):
    try:
        # 嘗試美式日期
        return pd.to_datetime(date_str, format="%m/%d/%Y %H:%M")
    except ValueError:
        try:
            # 如果失敗，改用歐洲格式
            return pd.to_datetime(date_str, format="%d/%m/%Y %H:%M")
        except:
            return pd.NaT

liw_feeder = pd.concat([liw_feeders_1, liw_feeders_2], axis=1)
liw_feeder = liw_feeder.loc[:, ~liw_feeder.columns.str.contains("Unnamed:")]
# 對整個 DataFrame 進行應用
liw_feeder["TimeStamp"] = liw_feeder["TimeStamp"].apply(parse_mixed_date)
liw_feeder = liw_feeder.dropna(subset=["TimeStamp"], how="any")

In [252]:
# contextual quality
logbook = pd.read_excel("MSOM data external sharing\Contextual quality data\Logbook Long Run Days.xlsx")
content = pd.read_excel("MSOM data external sharing\Contextual quality data\RM Content Uniformity.xlsx")
material_property = pd.read_excel("MSOM data external sharing\Contextual quality data\RM Material Properties.xlsx")
tablet_property = pd.read_excel("MSOM data external sharing\Contextual quality data\RM Tablet Properties and Drum Change.xlsx", sheet_name="Tablet properties", header=1)
drum_change = pd.read_excel("MSOM data external sharing\Contextual quality data\RM Tablet Properties and Drum Change.xlsx", sheet_name="Raw Material Drum change", header=1)

In [253]:
# tablet_property 處理
tablet_property = tablet_property.dropna(axis=0, how="all")

In [254]:
# drum_change 處理
api = drum_change.iloc[1:, 0:4].dropna(axis=0, how="all")
mgst = drum_change.iloc[1:, 4:8].dropna(axis=0, how="all")
lactose = drum_change.iloc[1:, 8:12].dropna(axis=0, how="all")
Ac_Di_Sol = drum_change.iloc[1:, 12:16].dropna(axis=0, how="all")
Avicel_102_PD1 = drum_change.iloc[1:, 16:20].dropna(axis=0, how="all")
Avicel_102_PD4 = drum_change.iloc[1:, 20:24].dropna(axis=0, how="all")

api = api[api["Est Refill time"] != "missing"]

In [298]:
# first day
# machine data
time_till_first_day = 60 * 60 * 15 + 60 * 17 - 5
liw_feeder = liw_feeder[:time_till_first_day]
blenders = blenders[:time_till_first_day]
pressor = pressor[:time_till_first_day]

# contextual data
api_first_day = api[:7]
mgst_first_day = mgst[:6]
lactose_first_day = lactose[:3]
Ac_Di_Sol_first_day = Ac_Di_Sol[:2]
Avicel_102_PD1_first_day = Avicel_102_PD1[:4]
Avicel_102_PD4_first_day = Avicel_102_PD4[:4]

          Date/Time.5  Amount (kg).5 Drum #.3    Est Refill time.5
1 2018-01-12 07:30:00           50.0    20649  2018-01-12 11:30:00
2 2018-01-12 11:35:00           50.0    20636  2018-01-12 15:00:00
3 2018-01-12 14:58:00           50.0    20634  2018-01-12 18:28:00
4 2018-01-12 18:13:00           50.0    20631  2018-01-12 21:43:00

In [300]:

time_set = {}

i = 0

# while i < len(api_first_day) - 1
liw_feeder[(liw_feeder["TimeStamp"] > api_first_day.iloc[i]["Date/Time"]) & (liw_feeder["TimeStamp"] < api_first_day.iloc[i+1]["Date/Time"])]

,TimeStamp,Feed Factor PD1,Feed Factor PD2,Feed Factor PD3,Feed Factor PD4,Feed Factor PD5,Feed Factor PD7,Screw RPM PD1,Screw RPM PD2,Screw RPM PD3,...,Net Weight PD3,Net Weight PD4,Net Weight PD5,Net Weight PD7,Totalizer PD1,Totalizer PD2,Totalizer PD3,Totalizer PD4,Totalizer PD5,Totalizer PD7
0,2018-01-12 08:43:00,1.3334,1.9152,1.3027,1.3089,1.1295,0.83728,0.0,0.0,0.0,...,0.42855,0.5205,0.8823,0.40355,2.5048,2.5454,0.87711,2.5031,0.26459,0.072622
1,2018-01-12 08:43:00,1.3334,1.9152,1.3027,1.3089,1.1295,0.83728,0.0,0.0,0.0,...,0.42855,0.52045,0.88225,0.40355,2.5048,2.5454,0.87711,2.5031,0.26459,0.072622
2,2018-01-12 08:43:00,1.3334,1.9152,1.3027,1.3089,1.1295,0.83728,0.0,0.0,0.0,...,0.42855,0.5205,0.8823,0.40355,2.5048,2.5454,0.87711,2.5031,0.26459,0.072622
3,2018-01-12 08:43:00,1.3334,1.9152,1.3027,1.3089,1.1295,0.83728,0.0,0.0,0.0,...,0.42855,0.5205,0.8823,0.40355,2.5048,2.5454,0.87711,2.5031,0.26459,0.072622
4,2018-01-12 08:43:00,1.3334,1.9152,1.3027,1.3089,1.1295,0.83728,0.0,0.0,0.0,...,0.42855,0.5205,0.88225,0.40355,2.5048,2.5454,0.87711,2.5031,0.26459,0.072622
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3294,2018-01-12 09:37:00,1.3466,1.9316,1.239,1.3321,1.1308,0.80357,176.4716,125.1521,65.6126,...,0.4674,0.645,0.9292,0.2311,12.0021,12.1901,4.2096,12.0059,1.2626,0.4055
3295,2018-01-12 09:37:00,1.3439,1.935,1.2402,1.3375,1.131,0.80339,176.9833,124.9474,65.5988,...,0.46595,0.6408,0.92815,0.2316,12.006,12.1941,4.211,12.0101,1.2631,0.40558
3296,2018-01-12 09:37:00,1.3475,1.9306,1.2447,1.3379,1.1311,0.80321,176.2158,125.0498,65.3371,...,0.4644,0.63665,0.92815,0.23085,12.01,12.1981,4.2125,12.0143,1.2635,0.40573
3297,2018-01-12 09:37:00,1.3444,1.9335,1.2484,1.3373,1.1311,0.80338,176.1135,124.7428,65.461,...,0.4633,0.63305,0.92825,0.23105,12.014,12.202,4.2133,12.0165,1.2638,0.40588
3298,2018-01-12 09:37:00,1.3449,1.9341,1.248,1.3351,1.1309,0.80271,176.1646,124.9474,65.3784,...,0.46185,0.62815,0.9265,0.2305,12.0179,12.206,4.2148,12.0208,1.2642,0.40603